import setuptools


with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="kryptobot",
    packages=[
        'kryptobot',
        'kryptobot.batches',
        'kryptobot.bots',
        'kryptobot.catalyst_extensions',
        'kryptobot.catalyst_extensions.bundles',
        'kryptobot.catalyst_extensions.exchange',
        'kryptobot.ccxt_shim',
        'kryptobot.db',
        'kryptobot.harvesters',
        'kryptobot.learners',
        'kryptobot.listeners',
        'kryptobot.markets',
        'kryptobot.notifiers',
        'kryptobot.portfolio',
        'kryptobot.publishers',
        'kryptobot.server',
        'kryptobot.signals',
        'kryptobot.strategies',
        'kryptobot.strategies.catalyst',
        'kryptobot.strategies.core',
        'kryptobot.strategies.t2',
        'kryptobot.ta',
        'kryptobot.workers',
        'kryptobot.workers.catalyst',
        'kryptobot.workers.core',
        'kryptobot.workers.batch',
        'kryptobot.workers.harvester',
        'kryptobot.workers.learner',
        'kryptobot.workers.strategy',
        'kryptobot.workers.t2',
    ],
    version="0.0.3",
    author="Stephan Miller",
    author_email="stephanmil@gmail.com",
    description="Cryptocurrency trading bot framework",
    long_description=long_description,
    url="https://github.com/eristoddle/KryptoBot",
    zip_safe=False,
    include_package_data=True,
    install_requires=[
          'pypubsub',
          'requests',
          'SQLAlchemy',
          'psycopg2-binary',
          'pyti',
          'ccxt',
          'redis',
          'celery',
          'flower',
          'kombu-encrypted-serializer',
          'celery-redbeat',
          'flask',
          'enigma-catalyst',
          'pandas',
          # This breaks, pymarketcap requires cython to be installed first
          'cython',
          'pymarketcap',
          'pandas',
          'ta-lib',
          'matplotlib',
          'mpl-finance',
          'structlog',
          'telegram',
          'tenacity',
          'slackweb',
          'webcord',
          'simplejson',
          'plotly',
          'cufflinks',
          'pivottablejs',
          'bokeh',
          'pydash'
    ],
    entry_points={
        'console_scripts': [
            'kryptobot = kryptobot.__main__:main',
        ],
    },
    classifiers=(
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
    ),
)
